version: '3.8'

services:
  backend:
    build:
      context: ./api
      dockerfile: dockerfile.dev
    ports:
      - "${BACKEND_PORT:-3005}:${BACKEND_PORT:-3005}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET=${SECRET}
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    ports:
      - "${FRONTEND_PORT:-3004}:3000"
    depends_on:
      - backend

  db:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
