# Imagen base de Node.js
FROM node:18-alpine

# Directorio de trabajo
WORKDIR /app/api

# Copiar archivos necesarios
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Exponer el puerto del backend
EXPOSE 3005

# Comando para iniciar la aplicación
CMD ["npm", "run", "dev"]
