# Imagen base de Node.js
FROM node:18-alpine

# Directorio de trabajo
WORKDIR /app

# Copiar archivos necesarios
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el código
COPY . .

# Exponer el puerto del backend
EXPOSE 3005

# Comando para iniciar la aplicación
CMD ["npm", "start"]
